# Site settings
title: Daryl M. Rush Builders
email: info@darylrush.com
description: One of a kind construction.
baseurl: "/"
url: "https://darylrush.com"
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-redirect-from
