# Site settings
title: Daryl M. Rush Builders
email: info@darylrush.com
description: One of a kind construction.
baseurl: "http://arenoir.github.io/darylrush.com"
url: "http://darylrush.com"
markdown: kramdown
